# -*- after-save-hook: (org-babel-tangle t); -*-
#+TITLE: Desktop
#+AUTHOR: Mathieu Marques
#+PROPERTY: header-args :mkdirp yes :results silent

Below are instructions to configure EXWM ie. Emacs as your window manager.
Blocks are automatically tangled on save from this very document. To see the
complete tangling parameters, consider browsing the raw version of this file.

* Desktop Entry

Enable Emacs in the list of eligible window managers.

#+BEGIN_SRC conf :tangle /sudo:://usr/share/xsessions/emacs.desktop
[Desktop Entry]
Comment=Emacs X Window Manager
Exec=emacs --debug-init --maximized
Name=EXWM
Type=Application
#+END_SRC

* Compositor

Set a compositor to handle complex graphic interactions eg. dragging,
transparency, shadows.

Identify the running compositor program.

#+BEGIN_SRC sh
inxi -Gxx | grep compositor
#+END_SRC

#+BEGIN_SRC emacs-lisp
paru -S picom-ibhagwan-git
#+END_SRC

* Screenshots

| TODO | Fix clipboard sharing from EXWM |

#+BEGIN_SRC sh
yay -S maim xclip
#+END_SRC

** Region

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.region.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --hidecursor --select \
    | xclip -selection clipboard -target image/png
#+END_SRC

** Region with Background Shadow

#+BEGIN_SRC sh
yay -S imagemagick
#+END_SRC

| TODO | Export to clipboard instead |

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.region-shadow.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --hidecursor --select \
    | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap \
              -background none -layers merge +repage shadow.png
#+END_SRC

** Window

#+BEGIN_SRC sh
yay -S xdotool
#+END_SRC

| TODO | =xdotool= is not able to retrieve the active window under EXWM |
| TODO | Make a shadow variant                                          |

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.window.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --window=$(xdotool getactivewindow) \
    | xclip -selection clipboard -target image/png
#+END_SRC

** Root

| TODO | Make a shadow variant |

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.root.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim | xclip -selection clipboard -target image/png
#+END_SRC

* Fonts

Enable aliasing and hinting presets.

#+BEGIN_SRC sh
rm -f /etc/fonts/conf.d/10-hinting-slight.conf
ln -s /etc/fonts/conf.avail/10-hinting-full.conf /etc/fonts/conf.d
ln -s /etc/fonts/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d
ln -s /etc/fonts/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d
ln -s /etc/fonts/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d
#+END_SRC

Uncomment FreeType hinting in =/etc/profile.d/freetype2.sh=.

#+BEGIN_SRC diff
-# export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
+export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
#+END_SRC

Set default font for classes in =/etc/fonts/local.conf=.

#+BEGIN_SRC xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test qual="any" name="family">
      <string>serif</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Robot Slab</string>
    </edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family">
      <string>sans-serif</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Roboto</string>
    </edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family">
      <string>monospace</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Hack</string>
    </edit>
  </match>
</fontconfig>
#+END_SRC

* Theme

#+BEGIN_SRC sh
yay -S materia-gtk-theme
#+END_SRC

Enable the theme in GTK settings files: =~/.config/gtk-3.0/settings.ini= and
=~/.config/gtk-4.0/settings.ini=.

#+BEGIN_SRC diff
+gtk-auto-mnemonics=0
+gtk-enable-mnemonics=0
#+END_SRC

* Notifications

#+BEGIN_SRC sh
paru -S dunst
#+END_SRC

Configure notification styles. Still experimenting with the options.

=~/.config/dunst/dunstrc=

#+BEGIN_SRC conf :tangle ~/.config/dunst/dunstrc
[global]
corner_radius = 4
font = Google Sans 14
geometry = "0x5-20+20"
horizontal_padding = 16
indicate_hidden = yes
monitor = 0
padding = 8
transparency = 90
#+END_SRC

* Zoom

Edit =~/.config/zoomus.conf= to disable the automatic mini-view since it will
eventually mess up your current window configuration.

#+BEGIN_SRC diff
-enableMiniWindow=true
+enableMiniWindow=false
#+END_SRC
