# -*- after-save-hook: (org-babel-tangle t); -*-
#+TITLE: Desktop
#+AUTHOR: Mathieu Marques
#+PROPERTY: header-args :results silent

Below are instructions to configure EXWM under an Arch-based distribution ie.
Emacs as your window manager. Blocks are automatically tangled on save from this
very document. To see the complete tangling parameters, consider browsing the
raw version of this file.

The instructions assume you have a working Linux distribution in the first
place.

* Desktop Entry

Enable Emacs in the list of eligible window managers.

#+BEGIN_SRC conf :tangle /sudo:://usr/share/xsessions/emacs.desktop
[Desktop Entry]
Comment=Emacs X Window Manager
Exec=dbus-launch --exit-with-session emacs --debug-init --maximized
Name=EXWM
Type=Application
#+END_SRC

* Screenshots

Export scripts to take screenshots in various contexts.

#+BEGIN_SRC sh
paru -S imagemagick maim xclip
#+END_SRC

** Region

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.region.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --hidecursor --select \
    | xclip -selection clipboard -target image/png
#+END_SRC

** Region with Background Shadow

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.region-shadow.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --hidecursor --select \
    | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap \
              -background none -layers merge +repage shadow.png
#+END_SRC

** Window

#+BEGIN_SRC sh
paru -S xdotool
#+END_SRC

| TODO | =xdotool= is not able to retrieve the active window under EXWM |
| TODO | Make a shadow variant                                          |

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.window.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim --window=$(xdotool getactivewindow) \
    | xclip -selection clipboard -target image/png
#+END_SRC

** Root

| TODO | Make a shadow variant |

#+HEADER: :shebang #!/bin/sh
#+HEADER: :tangle scripts/screenshot.root.sh
#+HEADER: :tangle-mode (identity #o755)
#+BEGIN_SRC sh
maim | xclip -selection clipboard -target image/png
#+END_SRC

* Extra

** Gnome

Once in a while I'll log in under something more stable -- read when I break my
system -- like Gnome.

Below are a couple settings to make the temporary excursion less
painful.

#+BEGIN_SRC sh
gsettings set org.gnome.desktop.peripherals.keyboard delay 200
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 20
gsettings set org.gnome.desktop.wm.preferences audible-bell false
#+END_SRC

** Zoom

Edit =~/.config/zoomus.conf= to disable the automatic mini-view since it will
eventually mess up your current window configuration.

#+BEGIN_SRC diff
-enableMiniWindow=true
+enableMiniWindow=false
#+END_SRC
