;; Colorful highlight for hex color strings
(defun me/highlight-hex-strings ()
  (interactive)
  (font-lock-add-keywords
   nil
   '(("#[abcdefABCDEF[:digit:]]\\{6\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background (match-string-no-properties 0)))))))
  (font-lock-fontify-buffer))
(add-hook 'emacs-lisp-mode-hook 'me/highlight-hex-strings)
(add-hook 'emmet-mode-hook 'me/highlight-hex-strings)
(add-hook 'python-mode-hook 'me/highlight-hex-strings)


;; Jazz palette (https://github.com/donderom/jazz-theme)
(defconst jazz/bg+3      "#606060" "Jazz palette: bg+3.")
(defconst jazz/bg+2      "#505050" "Jazz palette: bg+2.")
(defconst jazz/bg+1      "#202020" "Jazz palette: bg+1.")
(defconst jazz/bg        "#151515" "Jazz palette: bg.")
(defconst jazz/bg-1      "#101010" "Jazz palette: bg-1.")
(defconst jazz/blue+1    "#5C737C" "Jazz palette: blue+1.")
(defconst jazz/blue      "#385E6B" "Jazz palette: blue.")
(defconst jazz/cyan      "#34676F" "Jazz palette: cyan.")
(defconst jazz/fg        "#C6A57B" "Jazz palette: fg.")
(defconst jazz/green+1   "#7E9960" "Jazz palette: green+1.")
(defconst jazz/green     "#546A29" "Jazz palette: green.")
(defconst jazz/magenta   "#7F355E" "Jazz palette: magenta.")
(defconst jazz/orange    "#BA5B34" "Jazz palette: orange.")
(defconst jazz/red+1     "#8D4A4A" "Jazz palette: red+1.")
(defconst jazz/red       "#953331" "Jazz palette: red.")
(defconst jazz/yellow+1  "#96A62D" "Jazz palette: yellow+.")
(defconst jazz/yellow    "#909737" "Jazz palette: yellow.")


;; Solarized palette (http://ethanschoonover.com/solarized#the-values)
(defconst solarized/base03   "#002B36" "Solarized palette: base03.")
(defconst solarized/base02   "#073642" "Solarized palette: base02.")
(defconst solarized/base01   "#586E75" "Solarized palette: base01.")
(defconst solarized/base00   "#657B83" "Solarized palette: base00.")
(defconst solarized/base0    "#839496" "Solarized palette: base0.")
(defconst solarized/base1    "#93A1A1" "Solarized palette: base1.")
(defconst solarized/base2    "#EEE8D5" "Solarized palette: base2.")
(defconst solarized/base3    "#FDF6E3" "Solarized palette: base3.")
(defconst solarized/yellow   "#B58900" "Solarized palette: yellow.")
(defconst solarized/orange   "#CB4B16" "Solarized palette: orange.")
(defconst solarized/red      "#DC322F" "Solarized palette: red.")
(defconst solarized/magenta  "#D33682" "Solarized palette: magenta.")
(defconst solarized/violet   "#6C71C4" "Solarized palette: violet.")
(defconst solarized/blue     "#268BD2" "Solarized palette: blue.")
(defconst solarized/cyan     "#2AA198" "Solarized palette: cyan.")
(defconst solarized/green    "#859900" "Solarized palette: green.")


;; Zenburn palette (https://github.com/bbatsov/zenburn-emacs)
(defconst zenburn/bg+3      "#6F6F6F" "Zenburn palette: bg+3.")
(defconst zenburn/bg+2      "#5F5F5F" "Zenburn palette: bg+2.")
(defconst zenburn/bg+1      "#4F4F4F" "Zenburn palette: bg+1.")
(defconst zenburn/bg+05     "#494949" "Zenburn palette: bg+05.")
(defconst zenburn/bg        "#3F3F3F" "Zenburn palette: bg.")
(defconst zenburn/bg-05     "#383838" "Zenburn palette: bg-05.")
(defconst zenburn/bg-1      "#2B2B2B" "Zenburn palette: bg-1.")
(defconst zenburn/bg-2      "#000000" "Zenburn palette: bg-2.")
(defconst zenburn/blue+1    "#94BFF3" "Zenburn palette: blue+1.")
(defconst zenburn/blue      "#8CD0D3" "Zenburn palette: blue.")
(defconst zenburn/blue-1    "#7CB8BB" "Zenburn palette: blue-1.")
(defconst zenburn/blue-2    "#6CA0A3" "Zenburn palette: blue-2.")
(defconst zenburn/blue-3    "#5C888B" "Zenburn palette: blue-3.")
(defconst zenburn/blue-4    "#4C7073" "Zenburn palette: blue-4.")
(defconst zenburn/blue-5    "#366060" "Zenburn palette: blue-5.")
(defconst zenburn/cyan      "#93E0E3" "Zenburn palette: cyan.")
(defconst zenburn/fg+1      "#FFFFEF" "Zenburn palette: fg+1.")
(defconst zenburn/fg        "#DCDCCC" "Zenburn palette: fg.")
(defconst zenburn/fg-1      "#656555" "Zenburn palette: fg-1.")
(defconst zenburn/green+4   "#BFEBBF" "Zenburn palette: green+4.")
(defconst zenburn/green+3   "#AFD8AF" "Zenburn palette: green+3.")
(defconst zenburn/green+2   "#9FC59F" "Zenburn palette: green+2.")
(defconst zenburn/green+1   "#8FB28F" "Zenburn palette: green+1.")
(defconst zenburn/green     "#7F9F7F" "Zenburn palette: green.")
(defconst zenburn/green-1   "#5F7F5F" "Zenburn palette: green-1.")
(defconst zenburn/magenta   "#DC8CC3" "Zenburn palette: magenta.")
(defconst zenburn/orange    "#DFAF8F" "Zenburn palette: orange.")
(defconst zenburn/red+1     "#DCA3A3" "Zenburn palette: red+1.")
(defconst zenburn/red       "#CC9393" "Zenburn palette: red.")
(defconst zenburn/red-1     "#BC8383" "Zenburn palette: red-1.")
(defconst zenburn/red-2     "#AC7373" "Zenburn palette: red-2.")
(defconst zenburn/red-3     "#9C6363" "Zenburn palette: red-3.")
(defconst zenburn/red-4     "#8C5353" "Zenburn palette: red-4.")
(defconst zenburn/yellow    "#F0DFAF" "Zenburn palette: yellow.")
(defconst zenburn/yellow-1  "#E0CF9F" "Zenburn palette: yellow-1.")
(defconst zenburn/yellow-2  "#D0BF8F" "Zenburn palette: yellow-2.")
