#+TITLE: Setting Up Manjaro
#+AUTHOR: Mathieu Marques
#+PROPERTY: header-args :mkdirp yes :results silent

This file documents the steps I've followed to install my machine running
Manjaro.

| TODO | Add Arch instructions |

* Bootstrap

As well as core utilities (somehow not included by default).

#+BEGIN_SRC shell
pacman -S yay
yay -S base-devel
#+END_SRC

** Dot Files

Clone the =dot= repository and link configuration files to their corresponding
location following the README instructions.

#+BEGIN_SRC shell
git clone https://github.com/angrybacon/dot.git ~/Workspace/dot/
#+END_SRC

** Node.js

Install the Node version manager. See https://github.com/nvm-sh/nvm for more details.

#+BEGIN_SRC emacs-lisp
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
nvm install node
#+END_SRC

And install additional utilities =npm= and =yarn= globally in case packages
don't support NVM paths.

#+BEGIN_SRC shell
yay -S npm yarn
#+END_SRC

** Prompt

Install the =pure= promt.

#+BEGIN_SRC shell
yay -S zsh-pure-prompt-git
#+END_SRC

Add add the following setup to =~/.zshrc=.

#+BEGIN_SRC diff
+autoload -U promptinit; promptinit
+prompt pure
#+END_SRC

** Enable Asterisks During Password Prompts

Run =visudo= and add the =pwfeedback= option.

#+BEGIN_SRC diff
-Defaults env_reset
+Defaults env_reset,pwfeedback
#+END_SRC

** Increase the Key-Repeat Rate

Add the following setting to your shell profile eg. =~/.profile=.

#+BEGIN_SRC diff
+xset r rate 200 50
#+END_SRC

** Graphics

Identify the installed drivers with the preferred =mhwd= or =inxi=.

#+BEGIN_SRC shell
mhwd -li -d --pci
inxi -G
#+END_SRC

Identify the available drivers for the current configuration.

#+BEGIN_SRC shell
mhwd -l -d --pci
#+END_SRC

Install the recommended driver for the current configuration. If experiencing
issues related to the drivers, try switching between the =free= and =nonfree=
versions.

#+BEGIN_SRC shell
sudo mhwd -a pci free 0300
#+END_SRC

* Fonts

Install my favorite fonts.

#+BEGIN_SRC shell
yay -S \
    ttf-cascadia-code \
    ttf-google-sans \
    ttf-roboto \
    ttf-roboto-slab
#+END_SRC

* Emacs

Install the preferred =gccemacs=. Details at http://akrl.sdf.org/gccemacs.html.
CMake is necessary in order to compile the dependencies to =vterm= at runtime.

#+BEGIN_SRC shell
yay -S emacs-native-comp-git cmake
#+END_SRC

* SSH

#+BEGIN_SRC shell
yay -S openssh
ssh-keygen -t rsa -b 4096
#+END_SRC

* Other Utilities

#+BEGIN_SRC shell
yay -S \
    emoji-keyboard \
    htop \
    tree
#+END_SRC

* Other Applications

#+BEGIN_SRC shell
yay -S \
    brave chromium firefox-developer-edition \
    cockatrice \
    discord \
    piper \
    qbittorrent \
    signal-desktop \
    slack-desktop \
    spotify \
    vlc
#+END_SRC

** Plex

*** Dependencies

Install the server.

#+BEGIN_SRC shell
yay -S plex-media-server
#+END_SRC

*** Permissions

Create a mount point for an external drive named =Phoenix= that the =plex= user
will be able to access.

#+BEGIN_SRC shell
sudo mkdir -p /media/phoenix
sudo chmod -R /media
#+END_SRC

Retrieve the UUID of the drive (with =df= and =blkid= for instance) and add the
corresponding entry at the bottom of =/etc/fstab=.

#+BEGIN_SRC diff
+UUID=F8D2-30CF  /media/phoenix  exfat
#+END_SRC

Reboot and confirm that the drive is correctly mounted to the expected location.

*** Start the Service Automatically on Startup

Enable the server for future sessions automatically and optionally start it now.

#+BEGIN_SRC shell
systemctl start plexmediaserver.service
systemctl enable plexmediaserver.service
#+END_SRC

Visit http://localhost:32400/ and add the media libraries.

*** Fix the Claim Server Prompt

To grant writing permissions to the =plex= user on the preference file, first
stop the server.

#+BEGIN_SRC shell
systemctl stop plexmediaserver.service
#+END_SRC

Confirm the location of the preference file. It should be somewhere in
=/var/lib/plex/=. Then update its owner.

#+BEGIN_SRC shell
sudo chown -R plex:plex /var/lib/plex
#+END_SRC

Start the server again.

#+BEGIN_SRC shell
systemctl start plexmediaserver.service
#+END_SRC

** Steam

*** Dependencies

#+BEGIN_SRC shell
yay -S steam steam-native ttf-liberation wqy-zenhei
#+END_SRC
