#+TITLE: DotEmacs
#+AUTHOR: Mathieu Marques

This repository contains my personal Emacs configuration.

* What the .el

If you are wondering where has gone all of the Lisp, fear not, for it is
automagically tangled from an Org file into a Lisp file. See
[[./dotemacs.org][dotemacs.org]].

* Installation

#+BEGIN_QUOTE
Tested daily on Arch only.

I trust your Google-fu to make the most of the below instructions.
#+END_QUOTE

** Dependencies

| =jansson=  | Enable native JSON parsing              |
| =libvterm= | Used by terminal emulation within Emacs |
| =pinentry= | Let Emacs prompt for passphrases        |
| =ripgrep=  | Prefer =rg= over =grep=                 |

** Emacs

Clone the repository into your user directory.

#+BEGIN_SRC sh
git clone --recurse-submodules git@github.com:angrybacon/dotemacs.git ~/.config/emacs/
#+END_SRC

*** Linux

See [[https://github.com/angrybacon/dot/blob/master/LINUX.org#emacs]].

*** MacOS

Install Emacs 28 or above. I prefer
[[https://github.com/d12frosted/homebrew-emacs-plus][ =emacs-plus= ]] for its
additional compilation flags, specifically the ability not to have a title bar
ie. fake fullscreen since it has its downsides on macOS.

#+BEGIN_SRC sh
brew tap d12frosted/emacs-plus
brew install emacs-plus@28 --with-no-titlebar
#+END_SRC

** Icons

The mode-line utilizes features from =all-the-icons=.

Run the following when Emacs starts for the first time in order to download the
required fonts.

#+BEGIN_SRC
M-x all-the-icons-install-fonts RET
#+END_SRC

** Language Servers

In order for Emacs to connect to the LSP servers, install the language-specific
dependencies.

#+BEGIN_SRC sh
paru -S typescript-language-server
#+END_SRC

* Window Manager

Emacs can be used as a window manager under Linux. See
[[./DESKTOP.org][DESKTOP.org]].
