#+TITLE: DotEmacs
#+AUTHOR: Mathieu Marques

[[https://img.shields.io/github/license/angrybacon/dotemacs.svg?style=flat-square]]
[[https://img.shields.io/github/forks/angrybacon/dotemacs.svg?style=flat-square]]
[[https://img.shields.io/github/stars/angrybacon/dotemacs.svg?style=flat-square]]
[[https://img.shields.io/github/commit-activity/m/angrybacon/dotemacs.svg?style=flat-square&label=commits]]
[[https://img.shields.io/github/last-commit/angrybacon/dotemacs/master.svg?style=flat-square]]

[[https://img.shields.io/badge/archlinux-29.1-teal.svg?style=flat-square&logo=archlinux]]
[[https://img.shields.io/badge/macos-29.1-teal.svg?style=flat-square&logo=apple]]
[[https://img.shields.io/badge/windows-untested-red.svg?style=flat-square&logo=windows]]

This repository contains my personal Emacs configuration. I've kept it around
since my first hello-world through many /Emacs bankruptcies/ so it fits /me/ and
it might not fit /you/. Do feel free however to use it as your own, adapt it to
your needs. The licensing is /very/ permissive.

* Installation

#+BEGIN_QUOTE
Tested daily on Arch and MacOS.

I trust your Google-fu. Try and make the most of the below notes.
#+END_QUOTE

** Dependencies

| =jansson=     | Enable native JSON parsing             |
| =libvterm=    | Enable terminal emulation within Emacs |
| =pinentry=    | Enable pass prompts within Emacs       |
| =ripgrep=     | Prefer =rg= over =grep=                |
| =tree-sitter= | Enable built-in Tree-sitter bindings   |

** Emacs

Clone the repository into your user directory.

#+BEGIN_SRC sh
git clone git@github.com:angrybacon/dotemacs.git ~/.config/emacs/
#+END_SRC

There used to be Git submodules under =lisp/=. Since I'm basically the only
consumer of these packages and that they mostly exist to keep my configuration
clean, I don't plan on releasing any of them anytime soon. So they're back to
being simple directories for now.

The configuration is used daily under latest Emacs and doesn't guard against
undefined functions from earlier versions (by choice).

*** Linux

See [[https://github.com/angrybacon/dot/blob/master/LINUX.org#emacs]].

*** MacOS

See [[https://github.com/angrybacon/dot/blob/master/MACOS.org#emacs]].

** Language Servers

In order for Emacs to connect to the LSP servers, install the language-specific
dependencies.

#+BEGIN_SRC sh
paru -S typescript-language-server
#+END_SRC

* Window Manager

Emacs can be used as a window manager under Linux. See
[[./DESKTOP.org][DESKTOP.org]].
