;; Change the major mode strings
(delight 'css-mode               "css"            :major)
(delight 'dired-mode             "dired"          :major)
(delight 'dockerfile-mode        "dockerfile"     :major)
(delight 'emacs-lisp-mode        "elisp"          :major)
(delight 'eshell-mode            "eshell"         :major)
(delight 'fundamental-mode       "fundamental"    :major)
(delight 'gitattributes-mode     "gitattributes"  :major)
(delight 'gitconfig-mode         "gitconfig"      :major)
(delight 'gitignore-mode         "gitignore"      :major)
(delight 'help-mode              "help"           :major)
(delight 'html-mode              "html"           :major)
(delight 'js-mode                "js"             :major)
(delight 'lisp-interaction-mode  "lisp"           :major)
(delight 'magit-commit-mode      "magit-commit"   :major)
(delight 'magit-log-mode         "magit-log"      :major)
(delight 'magit-status-mode      "magit-status"   :major)
(delight 'markdown-mode          "markdown"       :major)
(delight 'org-mode               "org"            :major)
(delight 'python-mode            "python"         :major)
(delight 'scss-mode              "scss"           :major)
(delight 'text-mode              "text"           :major)
(delight 'web-mode               "web"            :major)


;; Change the minor mode strings
(delight 'autopair-mode               " autopair"               "autopair")
(delight 'company-mode                " company"                "company")
(delight 'eldoc-mode                  " eldoc"                  "eldoc-mode")
(delight 'emmet-mode                  " emmet"                  "emmet-mode")
(delight 'golden-ratio-mode           " golden-ratio"           "golden-ratio")
(delight 'highlight-parentheses-mode  " highlight-parentheses"  "highlight-parentheses")
(delight 'magit-auto-revert-mode      " magit"                  "magit")
(delight 'smooth-scroll-mode          " smooth-scroll"          "smooth-scroll")
(delight 'subword-mode                " subword"                "subword")


(provide 'init-mode-line)
