;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        electric-newline-and-maybe-indent
        emmet-expand-line
        emmet-next-edit-point
        forward-block
        indent-for-tab-command
        insert-parentheses
        kill-region
        markdown-exdent-or-delete
        me/goto-previous-block
        sgml-slash
        subword-left
        subword-right
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-visual-line
        eval-print-last-sexp
        mac-mwheel-scroll
        mac-previous-buffer
        mouse-drag-vertical-line
        mouse-save-then-kill
        mouse-set-region
        suspend-frame
        ))
